default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  # adapter: postgresql
  # encoding: utf8
  # pool: 5
test:
  <<: *default
  # # chenyang local
  # database: germanysky_production
  # host: localhost
  # username: root
  # password: "iii"
development:
  <<: *default
  # #chenyang local
  # database: germanysky_production
  # host: localhost
  # username: root
  # password: "iii"

  # #chenyang local
  # database: germanysky
  # host: localhost
  # username: root
  # password: "iii"

  # #Linode
  adapter: mysql2
  encoding: utf8mb4
  database: germanysky
  host: localhost
  username: root
  password: 771205

production:
  <<: *default
  ##Heroku
  # adapter: postgresql
  # encoding: utf8
  # pool: 5

  # #chenyang local
  database: germanysky
  host: localhost
  username: root
  password: "iii"

  # #Linode
  # adapter: mysql2
  # encoding: utf8mb4
  # database: germanysky
  # host: localhost
  # username: root
  # password: 771205